name: "Deploy Plugin"

on:
  workflow_call:
    inputs:
      plugin-name:
        required: true
        type: string
      plugin-repository:
        required: false
        type: string
        default: "codedynamis/PluginRepository"
    # secrets:
    #   DEPLOY_GITHUB_TOKEN:
    #     required: true

permissions:
  actions: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout Plugin Repository
        uses: actions/checkout@v3
        with:
          repository: "${{ inputs.plugin-repository }}"
          token: "${{ steps.generate-token.outputs.token }}"

      - name: Download Artifact (release)
        uses: actions/download-artifact@v3
        with:
          name: "${{ inputs.plugin-name }}"
          path: "dist/testing/${{ inputs.plugin-name }}"

      - name: Prepare commits.json
        run: |
          curl \
            -o dist/testing/${{ inputs.plugin-name }}/commits.json \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ steps.generate-token.outputs.token }}" \
            https://api.github.com/repos/${{ github.repository }}/commits
      - name: Prepare event.json
        run: echo '${{ toJSON(github.event) }}' > dist/testing/${{ inputs.plugin-name }}/event.json

      - name: Copy Artifact (stable)
        # if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        run: cp -rf dist/testing/${{ inputs.plugin-name }} dist/stable/

      - name: Push to Plugin Repository
        uses: stefanzweifel/git-auto-commit-action@v4
        continue-on-error: true
        with:
          commit_message: "Deploy ${{ inputs.plugin-name }} ${{ steps.version.outputs.value }}"
